(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
    '(package-selected-packages
         '(nov esxml pdf-tools tablist yapfify sphinx-doc pytest pyenv-mode py-isort pippel pipenv pyvenv pip-requirements lsp-python-ms lsp-pyright live-py-mode importmagic epc ctable concurrent deferred cython-mode company-anaconda blacken anaconda-mode pythonic insert-shebang flycheck-bashate fish-mode company-shell ob-restclient ob-http company-restclient restclient know-your-http-well stickyfunc-enhance srefactor ox-twbs reveal-in-osx-finder osx-trash osx-dictionary osx-clipboard launchctl easy-hugo esay-hugo shrink-path company helm helm-core magit transient dap-mode lsp-mode request markdown-mode spaceline org-plus-contrib evil mmm-mode lsp-ui geben company-phpactor phpactor composer php-runtime youdao-dictionary yasnippet-snippets yaml-mode xterm-color writeroom-mode winum which-key wgrep vterm vmd-mode valign uuidgen use-package undo-tree treemacs-projectile treemacs-persp treemacs-magit treemacs-icons-dired treemacs-evil toc-org terminal-here symbol-overlay string-inflection spaceline-all-the-icons smex shell-pop restart-emacs popwin phpcbf pcre2el password-generator paradox pangu-spacing overseer org-superstar org-rich-yank org-pomodoro org-mime org-cliplink open-junk-file nameless mvn multi-term move-text maven-test-mode markdown-toc magit-svn magit-section macrostep lsp-origami lsp-java lsp-ivy link-hint ivy-yasnippet ivy-xref ivy-purpose ivy-hydra ivy-avy indent-guide ibuffer-projectile hybrid-mode hungry-delete htmlize hl-todo highlight-parentheses highlight-numbers groovy-mode groovy-imports golden-ratio gnuplot gitignore-templates gitignore-mode gitconfig-mode gitattributes-mode git-timemachine git-messenger git-link ggtags fuzzy font-lock+ flyspell-correct-ivy flycheck-pos-tip flycheck-package flycheck-elsa flx find-by-pinyin-dired fcitx expand-region evil-visualstar evil-visual-mark-mode evil-tutor evil-textobj-line evil-surround evil-org evil-numbers evil-nerd-commenter evil-matchit evil-magit evil-lion evil-iedit-state evil-goggles evil-cleverparens evil-anzu eval-sexp-fu eshell-z eshell-prompt-extras esh-help emr emojify emoji-cheat-sheet-plus elisp-slime-nav editorconfig dumb-jump dotenv-mode doom-themes doom-modeline diminish devdocs counsel-projectile counsel-gtags company-statistics company-php company-lua company-emoji column-enforce-mode chinese-conv centered-cursor-mode bind-map auto-yasnippet auto-highlight-symbol auto-compile aggressive-indent ace-pinyin ace-link)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
